### ISSUE TITLE
RIOT API CHANGE

### ISSUE THREAD

**Issue by gigglearrows** [pseudonym117/Riot-Watcher#70] opened 2017-04-28 16:00 UTC
Note that Riot will change their api at the 24th of july 2017!
V1/V2 deprecation. quick overview:
* Riot games API domain changed to *.api.riotgames.com
* Standardization of all Riot Games API Endpoints
* Deprecation of aggregated stats endpoints
* Deprecation of batch API calls

**Comment by i32ropie** [comment] 2017-05-09 11:09
Actually now the static methodes aren't working... 
```>>> a = lol_api.static_get_champion_list(region='euw',locale='es_ES',champ_data=['all'],data_by_id=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/riotwatcher/riotwatcher.py", line 406, in static_get_champion_list
    champData=champ_data
  File "/usr/lib/python3.6/site-packages/riotwatcher/riotwatcher.py", line 396, in _static_request
    **kwargs
  File "/usr/lib/python3.6/site-packages/riotwatcher/riotwatcher.py", line 267, in base_request
    raise_status(r)
  File "/usr/lib/python3.6/site-packages/riotwatcher/riotwatcher.py", line 201, in raise_status
    raise LoLException(error_400, response)
riotwatcher.riotwatcher.LoLException: Bad request
```

**Comment by pseudonym117** [comment] 2017-07-17 04:46
duplicate of issue #71 - other issue has more discussion, so closing this one in favor of other defect

**Closed by pseudonym117** 2017-07-17 04:46 UTC
