### ISSUE TITLE
400/401 Client Error

### ISSUE THREAD

**Issue by BANALW** [pseudonym117/Riot-Watcher#201] opened 2021-12-07 11:28 UTC
When I tried to use 'lol_watcher.match.matchlist_by_puuid' and 'lol_watcher.match.by_id' function, it reported that "HTTPError: 400 Client Error: Bad Request for url: ......". But my api works well at Riot developer page. Can't figure out where is the problem.

**Comment by chamsom** [comment] 2021-12-09 17:13
Similar issue here, getting a Bad Request as well. @BANALW what does your Python look like?

`matches = watcher.match.matchlist_by_puuid(region, name['puuid'])`

`name` is currently storing a username on League. Unless, I have formatted wrong for the parameters? Please do let me know if you were able to make headway in resolving this issue somehow.

**Comment by chamsom** [comment] 2021-12-09 17:22
@BANALW Found out the issue...so if you have a global variable for the region, I suggest not using it. If you do keep it, make sure within `matches = watcher.match.matchlist_by_puuid(region, name['puuid'])` you specify `region = 'americas'`. I had set a global variable `region = na1` at the top of my code and as such, when passed as an argument to the parameter 'region' I received a 400/401 Request Error. This can be probably be closed now. 

E.g.
`matches = watcher.match.matchlist_by_puuid(region ='americas', puuid = name['puuid'])` This should return a list of matches.

**Comment by BANALW** [comment] 2021-12-10 11:26
> 

Thanks for the reply, I have tried the method you mentioned above, but I still get a 400/401 or 403 Error. My code is  `lol_watcher.match.matchlist_by_puuid('americas', '3cB0mJycwREAcSeVp5Yb35UhdvADtvHPHg2eQ0OEPGYkpfESiuq2GS0VUpCeMztYXWZVvnwp9PFONg')`. Then I got a 403 error.

If I add `region = ‘americas’`, I got a _positional argument follows keyword argument_ error.

**Comment by chamsom** [comment] 2021-12-14 17:41
Have you tried storing the username of interest in a variable called `name`?

For instance,

`name = watcher.summoner.by_name(region, '[Put usernames here without braces]')

ranked_stats = watcher.league.by_summoner(region, name['id'])
print(ranked_stats)
print('\n')
ranked_solo_stats = ranked_stats[0]`

**Comment by hingston** [comment] 2021-12-18 16:57
Should RiotWatcher include mapping for regions `na1 `-> `americas`? Or alternatively renaming the region argument here to make it clearer there's a difference?

**Comment by liadT22** [comment] 2021-12-22 15:10
The issue is that in other function region is represented as "eun1/na1...etc" but in this fucntion
the region is expected to be "EUROPE/AMERICA/ASIA"

**Comment by Josde** [comment] 2022-01-01 12:36
> Should RiotWatcher include mapping for regions `na1 `-> `americas`? Or alternatively renaming the region argument here to make it clearer there's a difference?

I guess an automatic mapping would be the best way to go, since AFAIK this is the only function that use these region names.  
By the way, in case someone finds this useful: As far as I'm seeing with my tests, Turkish and Russian API endpoints are grouped into "EUROPE", and Oceania is for some reason grouped into "AMERICAS".

**Comment by hingston** [comment] 2022-01-03 14:36
> The AMERICAS routing value serves NA, BR, LAN, LAS, and OCE. The ASIA routing value serves KR and JP. The EUROPE routing value serves EUNE, EUW, TR, and RU.

From https://developer.riotgames.com/apis#match-v5

I think an automatic mapping should be implemented. Otherwise, developers will all have to implement their own.

**Comment by heroofwastingtime** [comment] 2022-01-07 02:39
Hey guys! I am currently having a similar issue. 

`my_matches = watcher.match.matchlist_by_puuid(my_region, me['puuid'])
print(my_matches)`

'me' is storing my summoner info called by `watcher.summoner.by_name`

I had no issues getting this to run with v4, but v5 is truly proving to be the headache to work around.

**Comment by Silver15987** [comment] 2022-02-22 13:48
had the same issue, noticed that the API has different variables for the regions in match history for some reason. For 'euw1' it is europe, while for 'na1' it's americas.

**Comment by Washiii** [comment] 2022-04-05 03:02
Hey guys, i think that i might figured the problem out, while doing some coding i ran into the same problem, getting an error 400 doing a search for matches via puuid.

Traceback:
```bash
Traceback (most recent call last):
  File "C:\Users\pr0t\Desktop\PROJ\main.py", line 10, in <module>
    matches = match_parser(str(puuid)).parse()
  File "C:\Users\pr0t\Desktop\PROJ\api.py", line 15, in parse
    match = self.watcher.match.matchlist_by_puuid("americas", {self.puuid})
  File "C:\Users\pr0t\AppData\Roaming\Python\Python310\site-packages\riotwatcher\_apis\league_of_legends\MatchApiV5.py", line 79, in matchlist_by_puuid
    return self._request_endpoint(
  File "C:\Users\pr0t\AppData\Roaming\Python\Python310\site-packages\riotwatcher\_apis\NamedEndpoint.py", line 35, in _request_endpoint
    return self._base_api.raw_request(
  File "C:\Users\pr0t\AppData\Roaming\Python\Python310\site-packages\riotwatcher\_apis\BaseApi.py", line 51, in raw_request
    mod = handler.after_request(
  File "C:\Users\pr0t\AppData\Roaming\Python\Python310\site-packages\riotwatcher\Handlers\ThrowOnErrorHandler.py", line 20, in after_request
    raise ApiError(*err.args, request=err.request, response=err.response)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://americas.api.riotgames.com/lol/match/v5/matches/by-puuid/%7B'5K7iFI-DMF7lNX0JWQIxyhATymGNCW_ufHT0arJi8F9szGG86ZKBlqN7w4sAHOi-WQ0QbI7uMzX4Ow'%7D/ids
```

If you look at the last line of the traceback you will see that we have on the URL a %7B' and '%7D meaning that the API itself is creating a bad URL with some URL encoded characters (those being { and }).

I don't know why this is happening, i had a quick look into the code and nothing seemed "wrong" with it. Maybe the parsing on the [endpoint](https://github.com/pseudonym117/Riot-Watcher/blob/da95089e485333fa4fd960ea001409e731de42c9/src/riotwatcher/_apis/Endpoint.py) is messed up somehow, i didn't have a deep look into that but maybe that is the problem. I have tested this even hard coding a valid puuid to see if it was my error in some parsing with the summoner api but the results are the same.

This problem also happens in the [summoner via puuid search](https://github.com/pseudonym117/Riot-Watcher/blob/master/src/riotwatcher/_apis/league_of_legends/SummonerApiV4.py#L53)

**Comment by pseudonym117** [comment] 2022-04-05 05:26
For error codes:

## 400:
If you're getting this message, you've most likely entered an incorrect Summoner or Account ID. The most common cause is using an ID that does not belong to the API key you are currently using. It could also be caused by a poorly formed ID.

## 401:
This error indicates that the request being made did not contain the necessary authentication credentials (e.g., an API key) and therefore the client was denied access. Most likely cause is an API key has not been provided.

## 403:
possible causes:
- An invalid API key was provided with the API request
- A blacklisted API key was provided with the API request
- The API request was for an incorrect or unsupported path
  - This is quite common when providing the incorrect region to `match` endpoints, as riot has decided to change this from `na1`, `euw1`, `eune1`, etc to `americas`, `europe`, `asia`
  - Correct region for call and try again

Its possible that a remapper could be added to correct match endpoints. This hasnt been done historically because if riot decides to add a new region, a new version of `riotwatcher` will need to be published with an updated mapping. This unfortunately may be the best solution though... will look into feasibility.

**Comment by Washiii** [comment] 2022-04-05 07:18
@pseudonym117 I used a valid API key, i hardcoded my own puuid into the program and it didn't worked, checked it on riot website and then it workd, if you look the traceback you'll se that there are Url encoded characters that where not in my hardcoded puuid, i was using a valid region (americas) and again i was testing with my own puuid.

Here is the code that i was using if you want to see. I have removed my API key and also my nickname.

```python
from riotwatcher import LolWatcher, ApiError


class match_parser:
	def __init__(self, puuid):
		self.puuid = puuid
		self.API_KEY = "INSERT YOUR API KEY HERE"
		self.watcher = LolWatcher(self.API_KEY)
		self.user_region = "na1"

	def parse(self):
		matches = self.watcher.summoner.by_puuid("americas", {self.puuid})
		return matches



class puuid_parser:
	def __init__(self, name):
		self.name = name
		self.API_KEY = "INSERT YOUR API KEY HERE"
		self.watcher = LolWatcher(self.API_KEY)
		self.user_region = "na1"
		self.user = self.watcher.summoner.by_name(self.user_region, self.name)

	def parse(self):
		return self.user["puuid"]

puuid = puuid_parser("nickname").parse()
#or 
#puuid = "some valid puuid"

#code that errors:
print(match_parser(puuid).parse())
```

**Closed** 2022-04-25 07:49 UTC
