### ISSUE TITLE
API outdated

### ISSUE THREAD

**Issue by i32ropie** [pseudonym117/Riot-Watcher#55] opened 2016-03-09 16:28 UTC
There are some methodes not updated like [championmastery](https://developer.riotgames.com/api/methods#!/1071)

Are you going to update it? ^^

**Comment by fab0l1n** [comment] 2016-04-03 19:54
they changed the structure of the URL request so adding this properly into the watcher will be some work, but as a meantime solution add this to the RiotWatcher class:

    def get_champion_mastery(self, sum_id, region=None):
        if region is None:
            region = self.default_region
        args = {'api_key': self.key}
        print(args)
        r = requests.get(
            'https://{proxy}.api.pvp.net/championmastery/location/{platformId}/player/{summonerId}/champions'.format(
                proxy=region,
                platformId=platforms[region],
                summonerId=sum_id
            ),
            params=args
        )
        for lim in self.limits:
            lim.add_request()
        raise_status(r)
        return r.json()

This should return all entries of of champion masteries for a single SummonerId. at least for me it works.

**Comment by i32ropie** [comment] 2016-04-04 15:37
Thanks for your methode ^^

**Comment by pseudonym117** [comment] 2017-07-17 04:49
duplicate of issue #71 - that issue has more discussion and will be resolved soon. closing in favor of that defect. (also i have neglected these defects far too long)

**Closed by pseudonym117** 2017-07-17 04:49 UTC
